### ISSUE TITLE
想请教下，react native 怎么给按钮添加音效呢？用什么思路呢？

### ISSUE THREAD

**Issue by Stoneleee** [54sword/xiaoduyuReactNative#1]
如题，用react-native-video试了下，感觉不太好操作，不知道是不是我的打开方式不对，
另外我的项目没有使用redux，
期待作者提点下

**Comment by 54sword** [comment]
按钮添加声音，我也还未尝试过...
react native 上的 redux 和 react redux 基本一样，可以参考 https://github.com/Qwikly/react-native-router-redux

**Comment by Stoneleee** [comment]
好的 ，感谢。
